# Generated by Django 4.2.10 on 2024-05-15 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagname',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'Family'), (2, 'Friends'), (3, 'Trips')], default=0),
        ),
    ]
