# Generated by Django 4.2.10 on 2024-05-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_category_alter_tag_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagname',
            field=models.IntegerField(choices=[('general', 'General'), ('family', 'Family'), ('friends', 'Friends'), ('trips', 'Trips')], default=0),
        ),
    ]
