# Generated by Django 4.2.10 on 2024-05-16 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_tag_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagname',
            field=models.CharField(choices=[('general', 'General'), ('family', 'Family'), ('friends', 'Friends'), ('trips', 'Trips')], default='general'),
        ),
    ]
